### ISSUE TITLE
Resource `aws_iam_policy_attachment.ec2_ssm_attachment` causes conflicts with other resources in IAM 

### ISSUE THREAD

**Issue by JoeJasinski** [weka/terraform-aws-weka#162]
The following policy attachment was causing issues as it was trying to remove other attributes on the existing "ec2-ssm-attachment" (added somewhere else). Doing a "terrafrom plan" showed a lot of removals related to the "ec2-ssm-attachment". 

```hcl
resource "aws_iam_policy_attachment" "ec2_ssm_attachment" {
  name       = "ec2-ssm-attachment"
  roles      = [aws_iam_role.iam_role.name]
}
```

This change seemed to fix the issue, in my fork of this codebase, because it applies the policy to the role without involving the existing "ec2-ssm-attachment".

```hcl
resource "aws_iam_role_policy_attachment" "ec2_ssm_attachment" {
   policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
    role     = aws_iam_role.iam_role.name
}
```

Here is the relevant place in the code:
https://github.com/weka/terraform-aws-weka/blob/46603015877427f092eedbe7d0871f9ac634ed5b/modules/iam/ec2.tf#L150C12-L150C57

**Comment by assafgi** [comment]
Fixed in this release: https://github.com/weka/terraform-aws-weka/releases/tag/v1.0.6
